name: Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIP_INDEX_URL: "https://${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PASSWORD }}@sstp.jfrog.io/artifactory/api/pypi/pypi/simple"

    steps:
      - name: "Checkout the project..."
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Test
        run: ENV=unittest make test